name = "MiniPL"
uuid = "f1547c5b-f130-4a18-a8e9-547d91318662"
authors = ["Juha Myllari <jmyllari@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
